// <auto-generated />
using System;
using ForgeMission.Rooms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForgeMission.Rooms.Data.Migrations
{
    [DbContext(typeof(RoomsDbContext))]
    [Migration("20260717233324_DropLedgerAndPlatformKeysFromRooms")]
    partial class DropLedgerAndPlatformKeysFromRooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForgeMission.Rooms.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Issuer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_members_issuer_subject")
                        .HasFilter("subject IS NOT NULL");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("ForgeMission.Rooms.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ReplyTo")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_to");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("SenderKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sender_kind");

                    b.HasKey("Id");

                    b.HasIndex("ReplyTo");

                    b.HasIndex("SenderId");

                    b.HasIndex("RoomId", "CreatedAt")
                        .HasDatabaseName("ix_messages_room_id_created_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("ForgeMission.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("ForgeMission.Rooms.RoomInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RoomId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ux_room_invites_token");

                    b.ToTable("room_invites", (string)null);
                });

            modelBuilder.Entity("ForgeMission.Rooms.RoomMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("RoomId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ux_memberships_room_id_member_id");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("ForgeMission.Rooms.Message", b =>
                {
                    b.HasOne("ForgeMission.Rooms.Message", null)
                        .WithMany()
                        .HasForeignKey("ReplyTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ForgeMission.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgeMission.Rooms.Member", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ForgeMission.Rooms.MessagePayload", "Payload", b1 =>
                        {
                            b1.Property<Guid>("MessageId");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasJsonPropertyName("kind");

                            b1.Property<string>("Text")
                                .HasJsonPropertyName("text");

                            b1.Property<int>("V")
                                .HasJsonPropertyName("v");

                            b1.HasKey("MessageId");

                            b1.ToTable("messages");

                            b1
                                .ToJson("payload")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");

                            b1.OwnsOne("ForgeMission.Rooms.AgentMeta", "Agent", b2 =>
                                {
                                    b2.Property<Guid>("MessagePayloadMessageId");

                                    b2.Property<string>("Handle")
                                        .IsRequired()
                                        .HasJsonPropertyName("handle");

                                    b2.Property<int>("RetryCount")
                                        .HasJsonPropertyName("retryCount");

                                    b2.Property<int>("StepCount")
                                        .HasJsonPropertyName("stepCount");

                                    b2.Property<bool>("Verified")
                                        .HasJsonPropertyName("verified");

                                    b2.HasKey("MessagePayloadMessageId");

                                    b2.ToTable("messages");

                                    b2.HasJsonPropertyName("agent");

                                    b2.WithOwner()
                                        .HasForeignKey("MessagePayloadMessageId");

                                    b2.OwnsMany("ForgeMission.Rooms.AgentStep", "Trace", b3 =>
                                        {
                                            b3.Property<Guid>("AgentMetaMessagePayloadMessageId");

                                            b3.Property<int>("__synthesizedOrdinal")
                                                .ValueGeneratedOnAdd();

                                            b3.Property<int>("Attempt")
                                                .HasJsonPropertyName("attempt");

                                            b3.Property<string>("ExpertName")
                                                .IsRequired()
                                                .HasJsonPropertyName("expertName");

                                            b3.Property<string>("Reason");

                                            b3.Property<string>("Status")
                                                .IsRequired()
                                                .HasJsonPropertyName("status");

                                            b3.Property<string>("Text")
                                                .HasJsonPropertyName("text");

                                            b3.HasKey("AgentMetaMessagePayloadMessageId", "__synthesizedOrdinal");

                                            b3.ToTable("messages");

                                            b3.HasJsonPropertyName("trace");

                                            b3.WithOwner()
                                                .HasForeignKey("AgentMetaMessagePayloadMessageId");
                                        });

                                    b2.Navigation("Trace");
                                });

                            b1.Navigation("Agent");
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeMission.Rooms.Room", b =>
                {
                    b.OwnsOne("ForgeMission.Rooms.RoomMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("RoomId");

                            b1.Property<string>("Avatar")
                                .HasJsonPropertyName("avatar");

                            b1.Property<string>("Description")
                                .HasJsonPropertyName("description");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasJsonPropertyName("name");

                            b1.Property<int>("V")
                                .HasJsonPropertyName("v");

                            b1.HasKey("RoomId");

                            b1.ToTable("rooms");

                            b1
                                .ToJson("metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeMission.Rooms.RoomInvite", b =>
                {
                    b.HasOne("ForgeMission.Rooms.Member", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ForgeMission.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeMission.Rooms.RoomMembership", b =>
                {
                    b.HasOne("ForgeMission.Rooms.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgeMission.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
