// <auto-generated />
using System;
using ForgeMission.Rooms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForgeMission.Rooms.Data.Migrations
{
    [DbContext(typeof(RoomsDbContext))]
    partial class RoomsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForgeMission.Rooms.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.HasKey("Id");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("ForgeMission.Rooms.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid?>("ReplyTo")
                        .HasColumnType("uuid")
                        .HasColumnName("reply_to");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.Property<string>("SenderKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sender_kind");

                    b.HasKey("Id");

                    b.HasIndex("ReplyTo");

                    b.HasIndex("SenderId");

                    b.HasIndex("RoomId", "CreatedAt")
                        .HasDatabaseName("ix_messages_room_id_created_at");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("ForgeMission.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("ForgeMission.Rooms.RoomMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("RoomId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ux_memberships_room_id_member_id");

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("ForgeMission.Rooms.Message", b =>
                {
                    b.HasOne("ForgeMission.Rooms.Message", null)
                        .WithMany()
                        .HasForeignKey("ReplyTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ForgeMission.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgeMission.Rooms.Member", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ForgeMission.Rooms.MessagePayload", "Payload", b1 =>
                        {
                            b1.Property<Guid>("MessageId");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasJsonPropertyName("kind");

                            b1.Property<string>("Text")
                                .HasJsonPropertyName("text");

                            b1.Property<int>("V")
                                .HasJsonPropertyName("v");

                            b1.HasKey("MessageId");

                            b1.ToTable("messages");

                            b1
                                .ToJson("payload")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MessageId");
                        });

                    b.Navigation("Payload")
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeMission.Rooms.Room", b =>
                {
                    b.OwnsOne("ForgeMission.Rooms.RoomMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("RoomId");

                            b1.Property<string>("Avatar")
                                .HasJsonPropertyName("avatar");

                            b1.Property<string>("Description")
                                .HasJsonPropertyName("description");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasJsonPropertyName("name");

                            b1.Property<int>("V")
                                .HasJsonPropertyName("v");

                            b1.HasKey("RoomId");

                            b1.ToTable("rooms");

                            b1
                                .ToJson("metadata")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("ForgeMission.Rooms.RoomMembership", b =>
                {
                    b.HasOne("ForgeMission.Rooms.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForgeMission.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
