using System.Text.Json.Serialization;

namespace ForgeMission.Api;

// API A — mission invocation (42.6 task 5a). Message-based, not URL-shaped: see "API design —
// message-based" in docs/phases/phase-42.6-hosted-endpoint-ttfa.md for the full rationale and the
// locked invariants (M1-M10) these types implement. Naming follows the Amazon/ServiceStack
// convention — verb-named operation + XResponse — so a caller can infer the response type without
// consulting docs.

// ---------- Execute (the core operation) ----------

/// <summary>Run a mission once. M2: the mission handle is a field, never a route segment.</summary>
public sealed class ExecuteMission
{
    /// <summary>M3. PROTOCOL version — 0 means a pre-versioning client. Not the mission version.</summary>
    public int Version { get; set; }

    /// <summary>M7. Idempotency key, auto-generated by the CLI/SDK before send; a retry reuses it.</summary>
    public string ClientToken { get; set; } = "";

    /// <summary>"websearch" | "forge/websearch" — case-insensitive, Docker-style default namespace.
    /// See <see cref="MissionHandle"/>.</summary>
    public string Mission { get; set; } = "";

    /// <summary>Mission version/tag, distinct from <see cref="Version"/> (the protocol version).
    /// Null/absent means latest/currently-pinned.</summary>
    public string? MissionVersion { get; set; }

    /// <summary>Primary free-text input (maps to the runner's Goal).</summary>
    public string Input { get; set; } = "";

    /// <summary>Structured mission inputs (future — most missions read only <see cref="Input"/> today).</summary>
    public Dictionary<string, string>? Inputs { get; set; }

    /// <summary>Uploaded input artifact ids to stage for this run.</summary>
    public List<string>? InputArtifactIds { get; set; }

    /// <summary>M10. A message property, not an Accept header.</summary>
    public bool Stream { get; set; }
}

public sealed class ExecuteMissionResponse
{
    /// <summary>M6 — addressable independently of the connection that started the run.</summary>
    public string RunId { get; set; } = "";

    /// <summary>The RESOLVED handle — echoes what actually ran.</summary>
    public string Mission { get; set; } = "";

    /// <summary>Resolved version/OCI digest.</summary>
    public string MissionVersion { get; set; } = "";

    public string Answer { get; set; } = "";
    public bool Verified { get; set; }
    public List<MissionSource> Sources { get; set; } = [];
    public List<MissionTraceStep> Trace { get; set; } = [];
    public List<MissionArtifact> Artifacts { get; set; } = [];
    public MissionUsage Usage { get; set; } = new();

    /// <summary>M8 — usage/balance travel as response fields; an HTTP header is only a projection.</summary>
    public long BalanceMicroUsd { get; set; }

    /// <summary>M4.</summary>
    public ResponseStatus ResponseStatus { get; set; } = new();
}

public sealed class MissionUsage
{
    public long InputTokens { get; set; }
    public long OutputTokens { get; set; }
    public double ComputeSeconds { get; set; }
    public string? Model { get; set; }
    public long CostMicroUsd { get; set; }
}

/// <summary>Mirrors the engine's step envelope.</summary>
public sealed class MissionTraceStep
{
    public string Expert { get; set; } = "";
    public string Status { get; set; } = "";
    public string? Text { get; set; }
    public string? Reason { get; set; }
    public int Attempt { get; set; }
}

/// <summary>Mirrors Scout.SourceRef (src/ForgeMission.Scout/IWebSearch.cs) field-for-field — the
/// actual upstream type this is plumbed from once the runner contract carries structured citations
/// (see "Known gap: sources are not in the runner contract yet" in the phase-42.6 spoke). Provider
/// is non-nullable, matching SourceRef's own "source attribution over source-selection" tenet.</summary>
public sealed class MissionSource
{
    public string Url { get; set; } = "";
    public string? Title { get; set; }
    public string Provider { get; set; } = "";
    public double? ImpartialityRating { get; set; }
}

// ---------- Artifacts ----------

public sealed class UploadArtifact
{
    public int Version { get; set; }
    public string ClientToken { get; set; } = "";
    public string Name { get; set; } = "";
    public string ContentType { get; set; } = "";
    public long Size { get; set; }
    public string Sha256 { get; set; } = "";
}

public sealed class UploadArtifactResponse
{
    public MissionArtifact? Artifact { get; set; }
    public ResponseStatus ResponseStatus { get; set; } = new();
}

public sealed class GetArtifact
{
    public int Version { get; set; }
    public string ArtifactId { get; set; } = "";
}

public sealed class MissionArtifact
{
    public string Id { get; set; } = "";
    public string Name { get; set; } = "";
    public string ContentType { get; set; } = "";
    public long Size { get; set; }
    public string Sha256 { get; set; } = "";
    public string Role { get; set; } = "";
}

public static class ArtifactRole
{
    public const string Input = "input";
    public const string Output = "output";
}

// ---------- Streaming form (M10) ----------

public sealed class MissionRunEvent
{
    /// <summary>progress | heartbeat | result | error.</summary>
    public string Type { get; set; } = "";
    public string RunId { get; set; } = "";
    public MissionProgress? Progress { get; set; }

    /// <summary>Terminal — set only on the final "result" event.</summary>
    public ExecuteMissionResponse? Result { get; set; }
    public MissionArtifact? Artifact { get; set; }
    public ResponseStatus? ResponseStatus { get; set; }
}

public sealed class MissionProgress
{
    public string ExpertName { get; set; } = "";
    public string Kind { get; set; } = "";
    public string? Detail { get; set; }
    public int? ResultCount { get; set; }
}

// ---------- Catalog ----------

/// <summary>Backs `forge missions`.</summary>
public sealed class SearchMissions
{
    public int Version { get; set; }
    public string? Query { get; set; }
    public string? Publisher { get; set; }
}

public sealed class SearchMissionsResponse
{
    public List<MissionSummary> Results { get; set; } = [];
    public ResponseStatus ResponseStatus { get; set; } = new();
}

public sealed class MissionSummary
{
    public string Mission { get; set; } = "";
    public string Description { get; set; } = "";
    public string Publisher { get; set; } = "";
    public string Version { get; set; } = "";

    /// <summary>38.5 identity seal.</summary>
    public bool Verified { get; set; }
}

public sealed class GetMission
{
    public int Version { get; set; }
    public string Mission { get; set; } = "";

    /// <summary>Null == latest (same semantics as ExecuteMission.MissionVersion).</summary>
    public string? MissionVersion { get; set; }
}

/// <summary>Same shape as <see cref="MissionSummary"/>.</summary>
public sealed class GetMissionResponse
{
    public string Mission { get; set; } = "";
    public string Description { get; set; } = "";
    public string Publisher { get; set; } = "";
    public string Version { get; set; } = "";
    public bool Verified { get; set; }

    /// <summary>E.g. MissionNotFound.</summary>
    public ResponseStatus ResponseStatus { get; set; } = new();
}

// ---------- Account / run ----------

/// <summary>Backs `forge whoami`.</summary>
public sealed class GetAccount
{
    public int Version { get; set; }
}

public sealed class GetAccountResponse
{
    public string MemberId { get; set; } = "";

    /// <summary>Decided null for now — no data source exists without crossing the authbilling_db/
    /// rooms_db isolation boundary (userId is the only cross-context link, no cross-DB FK).</summary>
    public string? Email { get; set; }

    public long BalanceMicroUsd { get; set; }
    public ResponseStatus ResponseStatus { get; set; } = new();
}

/// <summary>M6.</summary>
public sealed class GetRun
{
    public int Version { get; set; }
    public string RunId { get; set; } = "";
}

public sealed class GetRunResponse
{
    public string RunId { get; set; } = "";

    /// <summary>Closed set: running | completed | failed. String-typed (not an enum) so the set can
    /// grow additively (M3) without breaking an older client's deserialization.</summary>
    public string Status { get; set; } = "";

    /// <summary>Populated when Status == completed.</summary>
    public ExecuteMissionResponse? Result { get; set; }

    /// <summary>E.g. RunNotFound.</summary>
    public ResponseStatus ResponseStatus { get; set; } = new();
}

/// <summary>Closed set for <see cref="GetRunResponse.Status"/> — new values are added here, not
/// invented ad hoc at the call site.</summary>
public static class RunStatus
{
    public const string Running = "running";
    public const string Completed = "completed";
    public const string Failed = "failed";
}

/// <summary>Transport-independent error codes — authoritative. The HTTP adapter projects these to
/// 404/402/401/400/403/500 as a convenience; the message is what's authoritative (M4). The spoke's
/// six-code list (MissionNotFound…RunFailed) didn't separately name a GetRun-not-found code, but its
/// own GetRunResponse doc comment says "e.g. RunNotFound" — an evident oversight, not a deliberate
/// choice to overload RunFailed (a 500) onto a 404 case. RunNotFound is added here as the same kind
/// of additive fix MissionNotFound already models — new values are added to the set, never invented
/// ad hoc at a call site (same rule <see cref="RunStatus"/> follows).</summary>
public static class ErrorCode
{
    public const string MissionNotFound = "MissionNotFound";
    public const string RunNotFound = "RunNotFound";
    public const string InsufficientCredit = "InsufficientCredit";
    public const string Unauthenticated = "Unauthenticated";
    public const string InvalidInput = "InvalidInput";
    public const string PolicyViolation = "PolicyViolation";
    public const string ArtifactNotFound = "ArtifactNotFound";
    public const string RunFailed = "RunFailed";
}

// ---------- Shared ----------

/// <summary>Matches ServiceStack.ResponseStatus/ResponseError verbatim (github.com/ServiceStack/
/// ServiceStack, src/ServiceStack.Interfaces/{ResponseStatus,ResponseError}.cs) — not a bespoke
/// shape. No TraceId field (correlation id lives in Meta, same as ServiceStack does it) and no
/// Warnings (was an orphan field with no defined use).</summary>
public sealed class ResponseStatus
{
    /// <summary>Null/empty == success.</summary>
    public string? ErrorCode { get; set; }
    public string? Message { get; set; }

    /// <summary>Only when server DebugMode is on; never in prod.</summary>
    public string? StackTrace { get; set; }

    /// <summary>Field-level validation errors, e.g. InvalidInput.</summary>
    public List<ResponseError>? Errors { get; set; }

    /// <summary>Additional context, e.g. Meta["traceId"].</summary>
    public Dictionary<string, string>? Meta { get; set; }

    public static ResponseStatus Ok() => new();

    public static ResponseStatus Fail(string errorCode, string message) =>
        new() { ErrorCode = errorCode, Message = message };
}

public sealed class ResponseError
{
    public string ErrorCode { get; set; } = "";
    public string FieldName { get; set; } = "";
    public string Message { get; set; } = "";
    public Dictionary<string, string>? Meta { get; set; }
}

// camelCase to match the framework's own default for the other four endpoints (minimal API's
// result-writer uses ASP.NET's ConfigureHttpJsonOptions default, camelCase) — ExecuteMission's
// manual JsonSerializer.SerializeToUtf8Bytes calls bypass that writer, so without this the wire
// was inconsistent: ExecuteMissionResponse came back PascalCase while GetAccount/SearchMissions/
// GetMission/GetRun came back camelCase. Caught while building the CLI client against the real
// deployed wire (2026-07-19) — case-insensitive on read regardless, but the emitted case must be
// one consistent thing for a hand-written client not to special-case per endpoint.
[JsonSourceGenerationOptions(PropertyNameCaseInsensitive = true, PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(ExecuteMission))]
[JsonSerializable(typeof(ExecuteMissionResponse))]
[JsonSerializable(typeof(MissionRunEvent))]
[JsonSerializable(typeof(UploadArtifact))]
[JsonSerializable(typeof(UploadArtifactResponse))]
[JsonSerializable(typeof(GetArtifact))]
[JsonSerializable(typeof(MissionArtifact))]
[JsonSerializable(typeof(SearchMissions))]
[JsonSerializable(typeof(SearchMissionsResponse))]
[JsonSerializable(typeof(GetMission))]
[JsonSerializable(typeof(GetMissionResponse))]
[JsonSerializable(typeof(GetAccount))]
[JsonSerializable(typeof(GetAccountResponse))]
[JsonSerializable(typeof(GetRun))]
[JsonSerializable(typeof(GetRunResponse))]
[JsonSerializable(typeof(ResponseStatus))]
internal partial class MessagesJsonContext : JsonSerializerContext;
